version: '3.8'

services:

  appslug:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'studoslug'
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html


  dbslug:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'studoslug'
      MYSQL_ROOT_PASSWORD: "toor"
